EXTENSION_NAME: "PSC"
VERSION: "0.4.12"
PROXY_HOST: "127.0.0.1"
PROXY_PORT: 7777
PROXY_USERNAME: ""
PROXY_PASSWORD: ""
PROXY_TIMEOUT: 5000
INTERVAL_TIME: 5000
HASH_MAP_LIMIT: 500
HASH_SET_LIMIT: 1000
SELECTED_HASH: false
SELECTED_PARAM: false
SELECTED_SMART: false
SELECTED_AUTH: false
TARGET_HOST_REGX: ""
BLACK_URL_REGX: "bing.com|baidu.com|microsoft.com|msn.com|nelreports.net|azure.com|bdstatic.com|logout"
BLACK_SUFFIX_REGX: "js|css|jpeg|gif|jpg|png|pdf|rar|zip|docx|doc|svg|jpeg|ico|woff|woff2|ttf|otf"
AUTH_INFO_REGX: "token|auth|sessid|session"
DEL_STATUS_REGX: "502|504"
DECODE_MAX_TIMES: 3
SHOW_MSG_LEVEL: 1